// templates/svelte-vite/src/App.svelte
<script>
  import Counter from "./lib/Counter.svelte";
</script>

<main>
  <h1>Hello from Bootnode</h1>
  <p class="sub">Svelte + Vite — edit <code>src/App.svelte</code>.</p>
  <Counter />
</main>

<style>
  main {
    padding: 2rem;
    font-family: system-ui, sans-serif;
    max-width: 40rem;
  }
  h1 {
    margin: 0 0 0.5rem;
  }
  .sub {
    color: #64748b;
    margin-bottom: 1.5rem;
  }
  code {
    background: #e2e8f0;
    padding: 0.1rem 0.35rem;
    border-radius: 0.25rem;
  }
</style>

// templates/web-dev/vue-vite/src/App.vue
<script setup>
import HelloWorld from "./components/HelloWorld.vue";
</script>

<template>
  <div class="layout">
    <HelloWorld />
    <p class="hint">
      Edit <code>src/App.vue</code> and add components under
      <code>src/components/</code>.
    </p>
  </div>
</template>

<style scoped>
.layout {
  padding: 2rem;
  max-width: 40rem;
}
.hint {
  margin-top: 1rem;
  color: #64748b;
  line-height: 1.6;
}
code {
  font-family: ui-monospace, monospace;
  background: #e2e8f0;
  padding: 0.1rem 0.35rem;
  border-radius: 0.25rem;
}
</style>
